hero_image: images/banner.png
description: Make a cursed profile wallpaper by tiling provided images in HTML
listed: false
pdf: false
title: 'Indieweb Loud Background Pattern'
landing: true
steps:
  - title: 'Start the background tiles'
  - title: 'Add another row'
  - title: 'Fill the background'
    completion:
      - 'engaged'
  - title: 'Add the warning note header'
    completion:
      - 'internal'
  - title: 'Add the final rumour'
    completion:
      - 'external'
