hero_image: images/banner.png
description: A short description of the project
listed: false
pdf: false
title: 'Indieweb Loud Background Pattern'
landing: true
steps:
  - title: 'Add the first loud stripes'
  - title: 'Make the pattern worse'
    completion:
      - 'engaged'
  - title: 'Add the note box'
    completion:
      - 'internal'
  - title: 'Style the heading and text'
    completion:
      - 'external'
